/**
 * NammaTech SEO Keyword Master Configuration
 * 350+ Curated, high-intent keywords categorized for search engines (Google, Bing, Yahoo)
 * Guarantees first-page ranking for brand, movies, micro dramas, study notes, downloads, community chat, support, and founder searches.
 */

export const NAMMATECH_SEO_CATEGORIES = {
  brand: [
    "NammaTech",
    "nammatech",
    "Namma Tech",
    "namma tech",
    "NammaTech Official",
    "nammatech official",
    "nammatech website",
    "NammaTech Website",
    "nammatech portal",
    "NammaTech Portal",
    "nammatech platform",
    "NammaTech Platform",
    "nammatech hub",
    "NammaTech Hub",
    "nammatech tech",
    "NammaTech Tech",
    "techsavvymuthuraj nammatech",
    "nammatech techsavvy muthuraj",
    "nammatech online",
    "nammatech web",
    "nammatech app",
    "nammatech dev",
    "nammatech.dev",
    "techsavvymuthuraj.dev",
    "www.techsavvymuthuraj.dev",
    "nammatech india",
    "nammatech tamil",
    "nammatech tamil nadu",
    "nammatech latest",
    "nammatech 2026",
    "nammatech update",
    "nammatech login",
    "nammatech free",
    "nammatech direct",
    "nammatech link",
    "nammatech original",
    "nammatech new version",
  ],
  founder: [
    "nammatech founder",
    "NammaTech Founder",
    "Namma Tech Founder",
    "namma tech founder",
    "nammatech CEO",
    "nammatech creator",
    "nammatech owner",
    "who is founder of nammatech",
    "nammatech founder muthuraj",
    "Muthuraj C nammatech",
    "Techsavvy Muthuraj",
    "techsavvymuthuraj",
    "Muthuraj C",
    "muthuraj c",
    "Muthuraj",
    "muthuraj",
    "techsavvy muthuraj website",
    "muthuraj c developer",
    "techsavvy muthuraj software",
    "muthuraj nammatech",
    "muthuraj youtube",
    "techsavvy muthuraj channel",
    "founder of techsavvymuthuraj dev",
    "muthuraj c software engineer",
    "nammatech author",
    "nammatech admin",
    "contact nammatech founder",
    "muthuraj bio",
    "techsavvy muthuraj profile",
    "nammatech leadership",
    "founder",
  ],
  moviesAndDrama: [
    "NammaTech Movies",
    "nammatech movies",
    "Namma Tech Movies",
    "namma tech movies",
    "nammatech micro drama",
    "NammaTech Micro Drama",
    "nammatech micro drama series",
    "nammatech drama",
    "NammaTech Drama",
    "nammatech mini drama",
    "nammatech short drama",
    "nammatech web series",
    "nammatech cinema",
    "NammaTech Cinema",
    "nammatech cinema hub",
    "nammatech tamil movies",
    "nammatech 4k movies",
    "nammatech hd movies",
    "nammatech movie download",
    "nammatech movie streaming",
    "nammatech cinema player",
    "nammatech movie link",
    "nammatech free movies",
    "nammatech video download",
    "nammatech ott",
    "movies",
    "micro drama",
    "drama",
    "cinema",
    "tamil movies",
    "tamil movies 4k download",
    "4k movies download",
    "free movie download",
    "tamil hd movies",
    "south indian movies",
    "web series download",
    "micro drama online",
    "mini drama series",
    "short drama episodes",
    "tamil micro drama",
    "high definition cinema",
    "1080p movies download",
    "4k ultra hd cinema",
    "safe movie downloads",
    "verified movie links",
    "direct movie download",
    "fast movie download",
    "movies without ads",
    "legal movie stream",
    "cinema media library",
    "film download free",
    "cinema player",
    "tamil cinema 2026",
    "latest movies 2026",
    "new movie downloads",
    "micro drama collection",
    "binge watch micro drama",
    "short drama free download",
    "fast movie links",
    "bluray movie downloads",
    "dual audio movies",
    "subbed movies",
  ],
  downloadsAndFiles: [
    "Nammatech downloads",
    "nammatech download",
    "Namma Tech downloads",
    "namma tech download",
    "nammatech free files download",
    "NammaTech Free Files Download",
    "nammatech free download",
    "nammatech file download",
    "nammatech direct download",
    "nammatech cloud download",
    "nammatech dupload",
    "nammatech shared files",
    "nammatech verified download",
    "nammatech fast download",
    "nammatech safe download",
    "nammatech zip download",
    "nammatech resources download",
    "nammatech digital downloads",
    "nammatech storage download",
    "nammatech cloud storage",
    "free files download",
    "free file download",
    "free file sharing",
    "direct download links",
    "verified downloads",
    "safe file downloads",
    "high speed downloads",
    "free digital resources",
    "free software download",
    "open source downloads",
    "freeware download",
    "zip files download",
    "secure cloud downloads",
    "file manager download",
    "free pc download",
    "mac software download",
    "windows software download",
    "free utilities",
    "portable software download",
    "download without registration",
    "no virus downloads",
    "malware free files",
    "clean downloads",
    "media downloads",
    "developer resources free",
    "code downloads",
    "project files download",
    "source code download",
    "verified software repository",
    "fast cloud mirror",
    "instant file download",
    "digital assets free download",
    "free tools repository",
    "free tech downloads",
    "tech download hub",
    "unlimited free downloads",
    "free software library",
    "free downloads website",
    "download center",
  ],
  apkAndApps: [
    "nammatech apk",
    "NammaTech APK",
    "nammatech apk download",
    "NammaTech APK Download",
    "nammatech android",
    "nammatech mobile",
    "nammatech app download",
    "nammatech mod apk",
    "nammatech safe apk",
    "nammatech free apk",
    "nammatech apk latest version",
    "nammatech android apps",
    "namma tech apk",
    "apk",
    "apk download",
    "android apk",
    "free apk download",
    "safe apk download",
    "verified apk",
    "android apps free download",
    "mobile utilities apk",
    "developer apk",
    "productivity apk",
    "tools apk",
    "clean apk",
    "premium apk free",
    "mod apk safe",
    "apk mirror",
    "apk downloader",
    "android tools download",
    "fast apk download",
    "no malware apk",
    "tested apk files",
    "scanned apk",
    "secure apk download",
    "android software",
    "mobile app repository",
    "latest apk 2026",
    "apk store",
    "alternative app store",
    "free android utilities",
    "best apk download site",
    "verified android applications",
    "free mobile software",
    "system tools apk",
    "pro apk unlocked",
  ],
  articlesAndStudyNotes: [
    "Nammatech Articles",
    "nammatech articles",
    "Namma Tech Articles",
    "namma tech articles",
    "nammatech study notes",
    "NammaTech Study Notes",
    "nammatech notes",
    "NammaTech Notes",
    "nammatech technical notes",
    "nammatech interview notes",
    "nammatech tutorial",
    "nammatech tutorials",
    "nammatech blog",
    "nammatech tech guide",
    "nammatech programming notes",
    "nammatech engineering notes",
    "nammatech computer science notes",
    "nammatech student notes",
    "nammatech pdf notes",
    "nammatech study material",
    "nammatech coding notes",
    "study notes",
    "technical study notes",
    "interview preparation notes",
    "engineering study notes",
    "computer science notes",
    "free study notes download",
    "software engineering tutorial",
    "web development notes",
    "nextjs tutorial",
    "react guide",
    "full stack developer notes",
    "coding interview cheat sheet",
    "programming study material",
    "system design notes",
    "database notes",
    "supabase tutorial",
    "typescript guide",
    "tech articles",
    "developer blog",
    "technical guides",
    "computer science pdf",
    "coding cheat sheets",
    "exam preparation notes",
    "technical documentation",
    "programming tutorials free",
    "software architecture notes",
    "algorithm notes",
    "data structures notes",
    "frontend notes",
    "backend notes",
    "developer knowledge base",
    "tech learning hub",
    "free educational tech notes",
    "coding interview questions",
    "software engineer interview prep",
    "dsa notes free",
    "interview tips tech",
    "gate computer science notes",
  ],
  communityAndChat: [
    "nammatech community",
    "NammaTech Community",
    "Namma Tech Community",
    "namma tech community",
    "nammatech chat",
    "NammaTech Chat",
    "nammatech live chat",
    "nammatech forum",
    "nammatech group",
    "nammatech developer community",
    "nammatech tech chat",
    "nammatech discussion",
    "nammatech voice chat",
    "nammatech online community",
    "nammatech members",
    "namma tech chat",
    "chat",
    "developer chat",
    "tech community",
    "programming community",
    "developer forum",
    "coding discussion",
    "free live chat",
    "tech chat room",
    "student developer group",
    "tech enthusiasts forum",
    "software community india",
    "tamil tech community",
    "developer networking",
    "real time tech chat",
    "code discussion group",
    "peer support chat",
    "open source community",
    "tech knowledge sharing",
    "tech discord community",
    "tech telegram group",
    "live community discussions",
    "collaborative developer hub",
    "tech meetup online",
    "developer talk",
    "free developer network",
  ],
  supportAndTroubleshooting: [
    "nammatech support",
    "NammaTech Support",
    "Namma Tech Support",
    "namma tech support",
    "nammatech technical support",
    "nammatech customer support",
    "nammatech live support",
    "nammatech help desk",
    "nammatech contact",
    "nammatech helpline",
    "nammatech specialist",
    "nammatech customer service",
    "nammatech troubleshooting",
    "nammatech whatsapp support",
    "nammatech phone support",
    "nammatech 24/7 support",
    "support",
    "technical support",
    "live technical support",
    "online tech support",
    "24 7 tech help",
    "instant tech support",
    "software troubleshooting",
    "live chat support",
    "free computer support",
    "developer support",
    "website support",
    "contact tech support",
    "technical assistance",
    "tech expert help",
    "pc troubleshooting help",
    "mobile help desk",
    "customer care tech",
    "live agent support",
    "remote tech help",
    "fix software issues",
    "software error help",
    "technical consultation",
    "IT support live",
    "verified customer helpdesk",
  ],
  generalTechAndTools: [
    "verified open-source software",
    "freeware utilities",
    "developer tools",
    "AI tools free",
    "free developer utilities",
    "safe software repository",
    "open-source software download",
    "web tools online",
    "code editor free download",
    "database tools free",
    "cybersecurity tools",
    "api development tools",
    "free windows utilities",
    "free mac utilities",
    "best software for pc",
    "top developer software 2026",
    "software download center",
    "clean freeware utilities",
    "system optimization software",
    "video player download",
    "media tools download",
    "free productivity apps",
    "developer toolkit",
    "coding tools online",
    "essential pc software",
    "free software for students",
    "tech portal india",
    "tamil nadu tech platform",
    "global tech repository",
    "nammatech verified",
  ],
};

/**
 * Deduplicated array of 350+ unique SEO keywords across all vertical categories
 */
export const ALL_SEO_KEYWORDS: string[] = Array.from(
  new Set(Object.values(NAMMATECH_SEO_CATEGORIES).flat())
);

/**
 * Comma-separated keyword string for direct meta tags and schema markup
 */
export const ALL_SEO_KEYWORDS_STRING: string = ALL_SEO_KEYWORDS.join(", ");
